name: 'nba_project'

profile: 'nba_project'

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  nba_dataset:
    +schema: raw

models:
  nba_project:
    +static_analysis: strict
    staging:
      +materialized: view
    marts:
      +materialized: table
