select
    year as season_year,
    tmID as team_id,
    franchID as franchise_id,
    lgID as league_id,
    name as team_name,
    confID as conference_id,
    divID as division_id,
    rank as league_rank,
    confRank as conference_rank,
    case when playoff is not null and playoff != '' then true else false end as made_playoffs,
    playoff as playoff_round,
    won as wins,
    lost as losses,
    won + lost as games_played,
    homeWon as home_wins,
    homeLost as home_losses,
    awayWon as away_wins,
    awayLost as away_losses,
    neutWon as neutral_wins,
    neutLoss as neutral_losses,
    confWon as conference_wins,
    confLoss as conference_losses,
    divWon as division_wins,
    divLoss as division_losses,
    o_fgm as team_field_goals_made,
    o_fga as team_field_goals_attempted,
    o_ftm as team_free_throws_made,
    o_fta as team_free_throws_attempted,
    o_3pm as team_three_pointers_made,
    o_3pa as team_three_pointers_attempted,
    o_oreb as team_offensive_rebounds,
    o_dreb as team_defensive_rebounds,
    o_reb as team_total_rebounds,
    o_asts as team_assists,
    o_pf as team_personal_fouls,
    o_stl as team_steals,
    o_blk as team_blocks,
    o_to as team_turnovers,
    o_pts as team_points,
    d_fgm as opponent_field_goals_made,
    d_fga as opponent_field_goals_attempted,
    d_ftm as opponent_free_throws_made,
    d_fta as opponent_free_throws_attempted,
    d_3pm as opponent_three_pointers_made,
    d_3pa as opponent_three_pointers_attempted,
    d_oreb as opponent_offensive_rebounds,
    d_dreb as opponent_defensive_rebounds,
    d_reb as opponent_total_rebounds,
    d_asts as opponent_assists,
    d_pf as opponent_personal_fouls,
    d_stl as opponent_steals,
    d_blk as opponent_blocks,
    d_to as opponent_turnovers,
    d_pts as opponent_points,
    pace,
    arena,
    attendance,
    min as total_minutes

from {{ source('nba_database', 'team_results') }}

where lgID = 'NBA'
and tmID is not null
and year is not null